{
'dateTimeForamt': 'iso8601',
'events': [

  {'start': '01 Feb 1877','title': 'E Zimerman', 'description': 'Name: E Zimerman<BR>Born: 28 Feb 1798<BR>Died: 1 Feb 1877<BR>', 'image': 'pond_springs_0013.png'},
  {'start': '01 Jan 1957','title': 'Jesus Garcia', 'description': 'Name: Jesus Garcia<BR>Born: 28 Feb 1883<BR>Died: 1 Jan 1957<BR>Note: husband of Lucy<BR>'},
  {'start': '10 Dec 1902','title': 'B.O. Gaddy', 'description': 'Name: B.O. Gaddy<BR>Born: 5 Apr 1881<BR>Died: 10 Dec 1902<BR>Marker Text: wife of W.B. Gaddy<BR>Note: "B.O.G" only, info from the 1964 transcription<BR>'},
  {'start': '10 Feb 1910','title': 'Viola Hunter', 'description': 'Name: Viola Hunter<BR>Born: 25 Nov 1887<BR>Died: 10 Feb 1910<BR>', 'image': 'pond_springs_0075.png'},
  {'start': '10 Jan 1892','title': 'Vivian Henry', 'description': 'Name: Vivian Henry<BR>Born: 30 Mar 1882<BR>Died: 10 Jan 1892<BR>Note: s/w Eula, badly eroded limestone<BR>', 'image': 'pond_springs_0097.png'},
  {'start': '10 Jan 1933','title': 'James R Bingham', 'description': 'Name: James R Bingham<BR>Born: 14 Dec 1878<BR>Died: 10 Jan 1933<BR>Note: s/w Flora A.<BR>'},
  {'start': '10 Jun 1928','title': 'William H Thompson', 'description': 'Name: William H Thompson<BR>Born: 11 May 1846<BR>Died: 10 Jun 1928<BR>Note: s/w Martha A. [Thompson]<BR>'},
  {'start': '10 Nov 1975','title': 'Walter Hunter', 'description': 'Name: Walter Hunter<BR>Born: 21 Sep 1891<BR>Died: 10 Nov 1975<BR>Marker Text: US Army WW I<BR>', 'image': 'pond_springs_0083.png'},
  {'start': '10 Sep 1937','title': 'Margaret Marie Faglie', 'description': 'Name: Margaret Marie Faglie<BR>Born: 24 May 1937<BR>Died: 10 Sep 1937<BR>Marker Text: "mother Eula Mae","father Doc", "granddaughter of A.J. Shannon"<BR>', 'image': 'pond_springs_0050.png'},
  {'start': '11 Nov 1912','title': 'Richard Lee Jackson', 'description': 'Name: Richard Lee Jackson<BR>Born: <BR>Died: 11 Nov 1912<BR>Marker Text: infant son of Claud and Clementine Jackson<BR>Note: son of Asa Claude Jackson and Laura Clementine Walden<BR>'},
  {'start': '12 Apr 1914','title': 'Mary F Walden', 'description': 'Name: Mary F Walden<BR>Born: 3 Oct 1850<BR>Died: 12 Apr 1914<BR>Note: s/w James A. Walden<BR>'},
  {'start': '12 Dec 1948','title': 'G B (Hamp) Hammack', 'description': 'Name: G B (Hamp) Hammack<BR>Born: 15 Jun 1877<BR>Died: 12 Dec 1948<BR>'},
  {'start': '12 Jul 1900','title': 'Edgar Earnest Lee', 'description': 'Name: Edgar Earnest Lee<BR>Born: 17 Aug 1896<BR>Died: 12 Jul 1900<BR>Marker Text: son of W.S. and L.A. Lee<BR>', 'image': 'pond_springs_0004.png'},
  {'start': '12 Mar 1892','title': 'Beulah [Lucy] Rutledge', 'description': 'Name: Beulah [Lucy] Rutledge<BR>Born: 22 Jan 1887<BR>Died: 12 Mar 1892<BR>Note: dau of John Walker Rutledge and Julia Elizabeth Anderson<BR>'},
  {'start': '12 Mar 1916','title': 'Lucy L Anderson', 'description': 'Name: Lucy L Anderson<BR>Born: 10 Aug 1828<BR>Died: 12 Mar 1916<BR>Note: s/w Thomas Anderson<BR>'},
  {'start': '12 Sep 1955','title': 'Dink Stewart', 'description': 'Name: Dink Stewart<BR>Born: [1878]<BR>Died: 12 Sep 1955<BR>Marker Text: age 77y, 1 mo, 14 d<BR>Note: stone gone, info from the 1964 transcription<BR>'},
  {'start': '13 Apr 1884','title': 'Marietta V Crumley', 'description': 'Name: Marietta V Crumley<BR>Born: 11 Apr 1883<BR>Died: 13 Apr 1884<BR>Marker Text: dau of S.I. And M.N. Crumley<BR>', 'image': 'pond_springs_0012.png'},
  {'start': '13 Aug 1896','title': 'Margaret S[avannah] Walden', 'description': 'Name: Margaret S[avannah] Walden<BR>Born: 15 Mar 1861<BR>Died: 13 Aug 1896<BR>Note: dau of Thomas Jefferson Nelson and Elizabeth Ann ODaniel<BR>'},
  {'start': '13 Dec 1892','title': 'Willie A[nn] Long', 'description': 'Name: Willie A[nn] Long<BR>Born: 10 Nov 1862<BR>Died: 13 Dec 1892<BR>Note: s/w Mary E. Oliver, J.B.J. Oliver, and Parrisade Oliver<BR>', 'image': 'pond_springs_0088.png'},
  {'start': '13 Feb 1927','title': 'Arther Petri', 'description': 'Name: Arther Petri<BR>Born: 3 Dec 1860<BR>Died: 13 Feb 1927<BR>', 'image': 'pond_springs_0069.png'},
  {'start': '13 May 1940','title': 'Paisley Glenn', 'description': 'Name: Paisley Glenn<BR>Born: 8 Feb 1855<BR>Died: 13 May 1940<BR>Note: son of Andrew Jackson Glenn and Nancy Nelson<BR>'},
  {'start': '13 Sep 1892','title': 'Laura Campbell', 'description': 'Name: Laura Campbell<BR>Born: 12 Feb 1868<BR>Died: 13 Sep 1892<BR>Note: stone broken<BR>', 'image': 'pond_springs_0030.png'},
  {'start': '14 Aug 1945','title': 'James A Walden', 'description': 'Name: James A Walden<BR>Born: 11 Oct 1849<BR>Died: 14 Aug 1945<BR>Note: s/w Mary F Walden<BR>'},
  {'start': '14 Dec 1993','title': 'Granville A Hammack', 'description': 'Name: Granville A Hammack<BR>Born: 1 Mar 1913<BR>Died: 14 Dec 1993<BR>Marker Text: Tec 5 US Army WW II<BR>Note: a mason<BR>'},
  {'start': '14 Jul 1924','title': 'Lillie Francis Cunningham', 'description': 'Name: Lillie Francis Cunningham<BR>Born: 21 Sep 1892<BR>Died: 14 Jul 1924<BR>'},
  {'start': '14 May 1904','title': 'Pinkie Ward', 'description': 'Name: Pinkie Ward<BR>Born: 24 Apr 1901<BR>Died: 14 May 1904<BR>Marker Text: dau of R.R. and C.A. Ward<BR>Note: s/w John Richard Ward<BR>', 'image': 'pond_springs_0055.png'},
  {'start': '14 May 1908','title': 'Clara Petri', 'description': 'Name: Clara Petri<BR>Born: 10 Jun 1856<BR>Died: 14 May 1908<BR>Marker Text: mother<BR>', 'image': 'pond_springs_0071.png'},
  {'start': '14 Nov 1915','title': 'Margaret L Thompson', 'description': 'Name: Margaret L Thompson<BR>Born: 7 Sep 1913<BR>Died: 14 Nov 1915<BR>Marker Text: dau of W.H and Annie L. Thompson<BR>'},
  {'start': '15 Nov 1913','title': 'Gottfried Ehrhardt', 'description': 'Name: Gottfried Ehrhardt<BR>Born: 20 Mar 1835<BR>Died: 15 Nov 1913<BR>Note: Father of Karl C. and Wilhelm Ehrhardt, both bur. in the Emmanuel Lutheran Church Cemetery in Pflugerville [eFPo]<BR>', 'image': 'pond_springs_0063.png'},
  {'start': '16 Apr 1929','title': 'Edna Earl Glenn', 'description': 'Name: Edna Earl Glenn<BR>Born: 14 Oct 1928<BR>Died: 16 Apr 1929<BR>Marker Text: dau of L.H and Mabel Glenn<BR>Note: dau of Louis Henry Glenn and Mabel Chloe Rutledge<BR>'},
  {'start': '16 Dec 1896','title': 'J[essie] B[laze] J[efferson] Oliver', 'description': 'Name: J[essie] B[laze] J[efferson] Oliver<BR>Born: 20 Dec 1811<BR>Died: 16 Dec 1896<BR>Note: s/w Mary E. Oiver, Willie A Long, and Parrisade Oliver<BR>', 'image': 'pond_springs_0087.png'},
  {'start': '16 Feb 1917','title': 'Martha J Heaton', 'description': 'Name: Martha J Heaton<BR>Born: 10 Jul 1844<BR>Died: 16 Feb 1917<BR>Note: s/w W.S. Heaton<BR>', 'image': 'pond_springs_0010.png'},
  {'start': '16 Mar 1974','title': 'W G (Pete) Hammack', 'description': 'Name: W G (Pete) Hammack<BR>Born: 28 Feb 1917<BR>Died: 16 Mar 1974<BR>'},
  {'start': '16 Nov 1915','title': 'W H Thompson', 'description': 'Name: W H Thompson<BR>Born: 15 Aug 1879<BR>Died: 16 Nov 1915<BR>'},
  {'start': '17 Apr 1936','title': 'Sarah E Cantwell', 'description': 'Name: Sarah E Cantwell<BR>Born: 27 Dec 1878<BR>Died: 17 Apr 1936<BR>Note: s/w John A. Cantwell, new stone has only years, full dates from 1964 transcription<BR>', 'image': 'pond_springs_0022.png'},
  {'start': '17 Aug 1905','title': 'Burney D Stewart', 'description': 'Name: Burney D Stewart<BR>Born: 9 Jan 1905<BR>Died: 17 Aug 1905<BR>', 'image': 'pond_springs_0015.png'},
  {'start': '17 Aug 1961','title': 'David Wayne Finley', 'description': 'Name: David Wayne Finley<BR>Born: 17 Aug 1961<BR>Died: 17 Aug 1961<BR>', 'image': 'pond_springs_0040.png'},
  {'start': '17 Jan 1880','title': 'Dasie D. Adams', 'description': 'Name: Dasie D. Adams<BR>Born: 25 Dec 1879<BR>Died: 17 Jan 1880<BR>Marker Text: dau of J.T. and N.A. Adams<BR>Note: stone gone, info from the 1964 transcription<BR>'},
  {'start': '17 Nov 1943','title': 'Sarah [Elizabeth] Glenn', 'description': 'Name: Sarah [Elizabeth] Glenn<BR>Born: 18 Sep 1857<BR>Died: 17 Nov 1943<BR>Note: wife of Paisely Glenn, dau of ?? Walden<BR>'},
  {'start': '17 Oct 1946','title': 'Ara C Walden', 'description': 'Name: Ara C Walden<BR>Born: 29 Nov 1870<BR>Died: 17 Oct 1946<BR>Marker Text: mother<BR>'},
  {'start': '17 Sep 1899','title': 'P[leasant] L Stewart', 'description': 'Name: P[leasant] L Stewart<BR>Born: 17 Sep 1834<BR>Died: 17 Sep 1899<BR>Note: husband of Agness, son of Nancy and Laban Stewart<BR>', 'image': 'pond_springs_0026.png'},
  {'start': '18 Feb 1965','title': 'Clara Hunter', 'description': 'Name: Clara Hunter<BR>Born: 7 Oct 1894<BR>Died: 18 Feb 1965<BR>', 'image': 'pond_springs_0082.png'},
  {'start': '18 Oct 1915','title': 'Alice Prewitt', 'description': 'Name: Alice Prewitt<BR>Born: 7 May 1874<BR>Died: 18 Oct 1915<BR>Marker Text: wife of E.N. Prewitt<BR>', 'image': 'pond_springs_0061.png'},
  {'start': '18 Sep 1934','title': 'Emily Viola Richards', 'description': 'Name: Emily Viola Richards<BR>Born: 24 Sep 1889<BR>Died: 18 Sep 1934<BR>'},
  {'start': '19 Feb 1896','title': 'Lucy A[nn] Lee', 'description': 'Name: Lucy A[nn] Lee<BR>Born: 25 Jul 1825<BR>Died: 19 Feb 1896<BR>Marker Text: relict of P.B. Lee<BR>Note: wife of Pleasant B. Lee, dau of Calvin Mims and Elizabeth Delk<BR>', 'image': 'pond_springs_0002.png'},
  {'start': '19 Jan 1918','title': 'Roy G. Lee', 'description': 'Name: Roy G. Lee<BR>Born: 26 Jan 1884<BR>Died: 19 Jan 1918<BR>', 'image': 'pond_springs_0064.png'},
  {'start': '19 Nov 1894','title': 'Agness Stewart', 'description': 'Name: Agness Stewart<BR>Born: 23 Aug 1834<BR>Died: 19 Nov 1894<BR>Note: name as "Agness" on the stone, wife of P.L. Stewart<BR>'},
  {'start': '19 Nov 1930','title': 'Charlsie A Ward', 'description': 'Name: Charlsie A Ward<BR>Born: 17 Jan 1858<BR>Died: 19 Nov 1930<BR>Note: wife of Richard Rhodes Ward, dau of Thomas Peel and Nancy Ann [Hutson?], second stone<BR>', 'image': 'pond_springs_0056.png'},
  {'start': '19 Sep 1890','title': 'Nancy Ellen McClure', 'description': 'Name: Nancy Ellen McClure<BR>Born: 8 Nov 1869<BR>Died: 19 Sep 1890<BR>Note: wife of Green<BR>', 'image': 'pond_springs_0036.png'},
  {'start': '19 Sep 1934','title': 'Laura J Walden', 'description': 'Name: Laura J Walden<BR>Born: 8 Sep 1875<BR>Died: 19 Sep 1934<BR>'},
  {'start': '31 Dec 1900','title': 'infants Rutledge', 'description': 'Name: infants Rutledge<BR>Born: <BR>Died: 1900<BR>Marker Text: 2 infant babies of Mancy and Addie Glenn Rutledge<BR>Note: infants of Manie Eugene Rutledge and Addie Lavena Glenn<BR>', 'image': 'pond_springs_0005.png'},
  {'start': '31 Dec 1903','title': 'James K[nox] P[olk] Shannon', 'description': 'Name: James K[nox] P[olk] Shannon<BR>Born: 19 Sep 1845<BR>Died: 1903<BR>Note: husband of Aslee, son of David Wilburn Shannon and Elizabeth Watkins<BR>', 'image': 'pond_springs_0047.png'},
  {'start': '31 Dec 1908','title': 'Lena Long', 'description': 'Name: Lena Long<BR>Born: 1871<BR>Died: 1908<BR>', 'image': 'pond_springs_0092.png'},
  {'start': '31 Dec 1920','title': 'Mildred Toungate', 'description': 'Name: Mildred Toungate<BR>Born: 1918<BR>Died: 1920<BR>', 'image': 'pond_springs_0052.png'},
  {'start': '31 Dec 1920','title': 'James R[iley] Warren', 'description': 'Name: James R[iley] Warren<BR>Born: 1917<BR>Died: 1920<BR>Note: husband of Mary Martha Estepp<BR>', 'image': 'pond_springs_0084.png'},
  {'start': '31 Dec 1923','title': 'Mary L Jackson', 'description': 'Name: Mary L Jackson<BR>Born: 1848<BR>Died: 1923<BR>Note: cracked<BR>', 'image': 'pond_springs_0038.png'},
  {'start': '31 Dec 1932','title': 'James B Hunter', 'description': 'Name: James B Hunter<BR>Born: 1856<BR>Died: 1932<BR>Marker Text: father<BR>Note: husband of Cornelia<BR>', 'image': 'pond_springs_0080.png'},
  {'start': '31 Dec 1933','title': 'Cornelia A[nn] Hunter', 'description': 'Name: Cornelia A[nn] Hunter<BR>Born: 1865<BR>Died: 1933<BR>Marker Text: mother<BR>Note: wife of James B. Hunter, dau of E.A. and M.F. Rutledge<BR>', 'image': 'pond_springs_0081.png'},
  {'start': '31 Dec 1933','title': 'Richard B Pointer', 'description': 'Name: Richard B Pointer<BR>Born: 1923<BR>Died: 1933<BR>', 'image': 'pond_springs_0023.png'},
  {'start': '31 Dec 1936','title': 'William F Long', 'description': 'Name: William F Long<BR>Born: 1859<BR>Died: 1936<BR>'},
  {'start': '31 Dec 1937','title': 'A. L. W', 'description': 'Name: A. L. W<BR>Born: <BR>Died: 1937<BR>Note: possibly another Ward<BR>'},
  {'start': '31 Dec 1938','title': 'Sarah C Lee', 'description': 'Name: Sarah C Lee<BR>Born: 1856<BR>Died: 1938<BR>', 'image': 'pond_springs_0067.png'},
  {'start': '31 Dec 1944','title': 'Nancy S Douglas', 'description': 'Name: Nancy S Douglas<BR>Born: 1848<BR>Died: 1944<BR>', 'image': 'pond_springs_0033.png'},
  {'start': '31 Dec 1946','title': '?? ??', 'description': 'Name: ?? ??<BR>Born: 16 Feb 1868<BR>Died: 1946<BR>'},
  {'start': '31 Dec 1946','title': 'Floyd W Hunter', 'description': 'Name: Floyd W Hunter<BR>Born: 1889<BR>Died: 1946<BR>', 'image': 'pond_springs_0074.png'},
  {'start': '31 Dec 1951','title': 'Robert F Eller', 'description': 'Name: Robert F Eller<BR>Born: 1865<BR>Died: 1951<BR>'},
  {'start': '31 Dec 1962','title': 'Jefferey G Jackson', 'description': 'Name: Jefferey G Jackson<BR>Born: 1893<BR>Died: 1962<BR>', 'image': 'pond_springs_0039.png'},
  {'start': '31 Dec 1963','title': 'Richard L Preece', 'description': 'Name: Richard L Preece<BR>Born: 1873<BR>Died: 1963<BR>Note: Wilkes-Clay funeral marker<BR>'},
  {'start': '31 Dec 1969','title': 'Pleas Randolph Eller', 'description': 'Name: Pleas Randolph Eller<BR>Born: 1883<BR>Died: 1969<BR>Note: stone gone, info from the 1975 transcription<BR>'},
  {'start': '31 Dec 1972','title': 'Doroteo H. Blanco', 'description': 'Name: Doroteo H. Blanco<BR>Born: 1895<BR>Died: 1972<BR>Note: stone gone, info from the 1975 transcription<BR>'},
  {'start': '31 Dec 1986','title': 'Cecil A Hunter', 'description': 'Name: Cecil A Hunter<BR>Born: 1892<BR>Died: 1986<BR>', 'image': 'pond_springs_0073.png'},
  {'start': '02 Apr 1967','title': 'William Oscar Warren', 'description': 'Name: William Oscar Warren<BR>Born: 25 Sep 1888<BR>Died: 2 Apr 1967<BR>Note: husband of Cora Agnes Warren, son of James Riley Warren and Mary Martha Estepp<BR>'},
  {'start': '02 Aug 1918','title': 'W[alter] G[reen] McClure', 'description': 'Name: W[alter] G[reen] McClure<BR>Born: 16 Mar 1876<BR>Died: 2 Aug 1918<BR>Note: husband of Bertha Lewis, son of Green and Susan McClure<BR>', 'image': 'pond_springs_0031.png'},
  {'start': '02 Aug 1977','title': 'Cora Agnes Warren', 'description': 'Name: Cora Agnes Warren<BR>Born: 7 Jun 1888<BR>Died: 2 Aug 1977<BR>Note: wife of William Oscar Warren, dau of John Paisley Glenn and Sarah Elizabeth Warren<BR>'},
  {'start': '02 Feb 1925','title': 'Lydia M Eller', 'description': 'Name: Lydia M Eller<BR>Born: 29 Mar 1869<BR>Died: 2 Feb 1925<BR>Note: sunken stone<BR>', 'image': 'pond_springs_0029.png'},
  {'start': '02 Jun 1948','title': 'Carothers', 'description': 'Name: Carothers<BR>Born: 1 Jun 1948<BR>Died: 2 Jun 1948<BR>Marker Text: baby boy<BR>', 'image': 'pond_springs_0076.png'},
  {'start': '02 Oct 1922','title': 'Annie Jackson', 'description': 'Name: Annie Jackson<BR>Born: 29 Mar 1879<BR>Died: 2 Oct 1922<BR>', 'image': 'pond_springs_0086.png'},
  {'start': '20 Aug 1890','title': 'Mary E Oliver', 'description': 'Name: Mary E Oliver<BR>Born: 3 Dec 1857<BR>Died: 20 Aug 1890<BR>Note: s/w Willie A Long, J.B.J. Oliver, and Parrisade Oliver<BR>', 'image': 'pond_springs_0088.png'},
  {'start': '20 Dec 1886','title': 'Wade Jr Henry', 'description': 'Name: Wade Jr Henry<BR>Born: 6 Dec 1886<BR>Died: 20 Dec 1886<BR>', 'image': 'pond_springs_0099.png'},
  {'start': '20 Dec 1936','title': 'Lucy Garcia', 'description': 'Name: Lucy Garcia<BR>Born: 19 Jun 1890<BR>Died: 20 Dec 1936<BR>Note: wife of Jesus<BR>'},
  {'start': '20 Jul 1883','title': 'Ann Buttery', 'description': 'Name: Ann Buttery<BR>Born: [1806]<BR>Died: 20 Jul 1883<BR>Marker Text: age 77 years<BR>Note: no stone, info from the 1964 transcription<BR>'},
  {'start': '20 Jun 1894','title': 'Louis E Houghton', 'description': 'Name: Louis E Houghton<BR>Born: 29 May 1873<BR>Died: 20 Jun 1894<BR>Marker Text: son of T.M. and Annie E. Houghton<BR>'},
  {'start': '20 May 1911','title': 'A J McKamy', 'description': 'Name: A J McKamy<BR>Born: 23 Sep 1866<BR>Died: 20 May 1911<BR>'},
  {'start': '20 Nov 1925','title': 'John Franklin', 'description': 'Name: John Franklin<BR>Born: 8 Mar 1853<BR>Died: 20 Nov 1925<BR>'},
  {'start': '22 Aug 1921','title': 'Edna Lou Chapman', 'description': 'Name: Edna Lou Chapman<BR>Born: <BR>Died: 22 Aug 1921<BR>Marker Text: dau of J.L. Chapman and Julia May Riff<BR>Note: no stone, info from the Williamson County [Tx] Death Records, Book 2<BR>'},
  {'start': '22 Oct 1899','title': 'Calvin Champion', 'description': 'Name: Calvin Champion<BR>Born: 23 Aug 1823<BR>Died: 22 Oct 1899<BR>', 'image': 'pond_springs_0011.png'},
  {'start': '23 Apr 1923','title': 'Bertha Henry', 'description': 'Name: Bertha Henry<BR>Born: 7 Jul 1899<BR>Died: 23 Apr 1923<BR>'},
  {'start': '23 Dec 1885','title': '?? Shannon', 'description': 'Name: ?? Shannon<BR>Born: 23 Dec 1885<BR>Died: 23 Dec 1885<BR>Marker Text: son of J.A. Shannon<BR>Note: stone gone, info from the 1964 transcription<BR>'},
  {'start': '23 Feb 1932','title': 'S[usan] C[atherine] McClure', 'description': 'Name: S[usan] C[atherine] McClure<BR>Born: 25 Dec 1840<BR>Died: 23 Feb 1932<BR>Marker Text: "Mrs."<BR>Note: dau of Laban and Nancy Stewart<BR>', 'image': 'pond_springs_0032.png'},
  {'start': '23 Jan 1884','title': 'M.B. Shannon', 'description': 'Name: M.B. Shannon<BR>Born: [1837]<BR>Died: 23 Jan 1884<BR>Marker Text: age 46y, 1m, 3d<BR>Note: stone damaged, name from the 1964 transcription<BR>', 'image': 'pond_springs_0046.png'},
  {'start': '24 Dec 1960','title': 'Thomas Herbert Eller', 'description': 'Name: Thomas Herbert Eller<BR>Born: 5 May 1886<BR>Died: 24 Dec 1960<BR>', 'image': 'pond_springs_0041.png'},
  {'start': '24 Jul 1889','title': 'Fannie King', 'description': 'Name: Fannie King<BR>Born: 11 Apr 1875<BR>Died: 24 Jul 1889<BR>Note: stone broken<BR>', 'image': 'pond_springs_0017.png'},
  {'start': '24 Mar 1892','title': 'Spencer Boateright', 'description': 'Name: Spencer Boateright<BR>Born: 28 Feb 1861<BR>Died: 24 Mar 1892<BR>Note: "Boateright" on stone, son of John L. Boatright and Lydia Sparks<BR>', 'image': 'pond_springs_0100.png'},
  {'start': '24 Mar 1933','title': 'M. E. White', 'description': 'Name: M. E. White<BR>Born: 7 Sep 1847<BR>Died: 24 Mar 1933<BR>Note: s/w P.L. White<BR>'},
  {'start': '25 Jan 1932','title': 'Bird Ward', 'description': 'Name: Bird Ward<BR>Born: 1898<BR>Died: 25 Jan 1932<BR>Note: child of Charlsie Ann and Richard Rhodes Ward<BR>'},
  {'start': '25 Jun 1958','title': 'Flora A Bingham', 'description': 'Name: Flora A Bingham<BR>Born: 10 Feb 1888<BR>Died: 25 Jun 1958<BR>Note: s/w James R.<BR>'},
  {'start': '25 May 1959','title': 'Frank Jackson', 'description': 'Name: Frank Jackson<BR>Born: 2 Oct 1867<BR>Died: 25 May 1959<BR>', 'image': 'pond_springs_0085.png'},
  {'start': '26 Feb 1922','title': 'Chas Petri', 'description': 'Name: Chas Petri<BR>Born: 12 Feb 1849<BR>Died: 26 Feb 1922<BR>Marker Text: father<BR>', 'image': 'pond_springs_0070.png'},
  {'start': '26 Feb 1922','title': 'James Warick Tuttle', 'description': 'Name: James Warick Tuttle<BR>Born: <BR>Died: 26 Feb 1922<BR>Marker Text: son of Wilver Harrison Tuttle and Dorothy Clifton<BR>Note: no stone, info from the Williamson County [Tx] Death Records, Book 2<BR>'},
  {'start': '26 Jan 1894','title': 'John Brooks', 'description': 'Name: John Brooks<BR>Born: 10 Aug 1825<BR>Died: 26 Jan 1894<BR>Note: shattered stone, last name and b. from 1964 transcription<BR>', 'image': 'pond_springs_0043.png'},
  {'start': '26 May 1930','title': 'Mary Alice Hartson', 'description': 'Name: Mary Alice Hartson<BR>Born: 10 Dec 1852<BR>Died: 26 May 1930<BR>Note: wife of Hiram Hartson, dau of E.A. and M.F. Rutledge<BR>'},
  {'start': '26 Oct 1939','title': 'May Anderson', 'description': 'Name: May Anderson<BR>Born: 7 May 1886<BR>Died: 26 Oct 1939<BR>', 'image': 'pond_springs_0068.png'},
  {'start': '26 Sep 1898','title': 'Joseph Decker', 'description': 'Name: Joseph Decker<BR>Born: 14 Sep 1898<BR>Died: 26 Sep 1898<BR>', 'image': 'pond_springs_0095.png'},
  {'start': '27 Apr 1890','title': 'William P., Sr. Rutledge', 'description': 'Name: William P., Sr. Rutledge<BR>Born: 29 Jul 1815<BR>Died: 27 Apr 1890<BR>Note: son of James Rutledge and Nancy Armstrong<BR>', 'image': 'pond_springs_0007.png'},
  {'start': '27 Aug 1933','title': 'Nelson', 'description': 'Name: Nelson<BR>Born: <BR>Died: 27 Aug 1933<BR>Marker Text: baby boy<BR>', 'image': 'pond_springs_0077.png'},
  {'start': '27 Jun 1885','title': 'Laban Stewart', 'description': 'Name: Laban Stewart<BR>Born: 14 Jun 1803<BR>Died: 27 Jun 1885<BR>Marker Text: age 82 years 13 days<BR>Note: husband of Nancy<BR>'},
  {'start': '27 Oct 1860','title': 'Jacob Leonce Glenn', 'description': 'Name: Jacob Leonce Glenn<BR>Born: 10 Apr 1860<BR>Died: 27 Oct 1860<BR>Note: son of Andrew Jackson Glenn and Nancy Nelson<BR>'},
  {'start': '27 Oct 1890','title': 'John Boateright', 'description': 'Name: John Boateright<BR>Born: 5 Mar 1831<BR>Died: 27 Oct 1890<BR>Note: stone gone, info from the 1964 transcription<BR>'},
  {'start': '27 Oct 1933','title': 'P. L. White', 'description': 'Name: P. L. White<BR>Born: 3 Apr 1850<BR>Died: 27 Oct 1933<BR>Note: s/w M.E. White<BR>'},
  {'start': '28 Apr 1885','title': 'Benn Franklin', 'description': 'Name: Benn Franklin<BR>Born: 28 Feb 1885<BR>Died: 28 Apr 1885<BR>Marker Text: son of John and Ann Franklin<BR>Note: "Benn" on stone<BR>'},
  {'start': '28 Apr 1887','title': 'Parrisade Oliver', 'description': 'Name: Parrisade Oliver<BR>Born: [1825]<BR>Died: 28 Apr 1887<BR>Marker Text: age 62 years<BR>Note: s/w Mary E. Oliver, Willie A Long, and J.B.J. Oliver<BR>', 'image': 'pond_springs_0087.png'},
  {'start': '28 Dec 1968','title': 'Rose Elizabeth Barnett', 'description': 'Name: Rose Elizabeth Barnett<BR>Born: 14 Nov 1892<BR>Died: 28 Dec 1968<BR>', 'image': 'pond_springs_0042.png'},
  {'start': '28 Nov 1891','title': 'Eula V Henry', 'description': 'Name: Eula V Henry<BR>Born: 14 Mar 1889<BR>Died: 28 Nov 1891<BR>Note: s/w Vivian, badly eroded limestone, 1964 transcription says b. 21 Nov 1888<BR>', 'image': 'pond_springs_0098.png'},
  {'start': '29 Apr 1888','title': 'W. A. King', 'description': 'Name: W. A. King<BR>Born: 28 Dec 1812<BR>Died: 29 Apr 1888<BR>Note: a mason, stone broken<BR>', 'image': 'pond_springs_0021.png'},
  {'start': '29 Apr 1905','title': 'Fannie R Stewart', 'description': 'Name: Fannie R Stewart<BR>Born: 28 Mar 1872<BR>Died: 29 Apr 1905<BR>', 'image': 'pond_springs_0016.png'},
  {'start': '29 Dec 1899','title': 'Sarah Houghton', 'description': 'Name: Sarah Houghton<BR>Born: 12 Sep 1872<BR>Died: 29 Dec 1899<BR>Marker Text: wife of Dr. W. M. Houghton<BR>Note: a mason<BR>'},
  {'start': '29 Dec 1921','title': 'Ethel Davis', 'description': 'Name: Ethel Davis<BR>Born: <BR>Died: 29 Dec 1921<BR>Marker Text: dau of Wm. Norris Davis and Ruth Jackson<BR>Note: no stone, info from the Williamson County [Tx] Death Records, Book 2<BR>'},
  {'start': '29 Jan 1884','title': 'Wilson Woody', 'description': 'Name: Wilson Woody<BR>Born: 28 Sep 1824<BR>Died: 29 Jan 1884<BR>', 'image': 'pond_springs_0062.png'},
  {'start': '29 Jul 1929','title': 'W B Glenn', 'description': 'Name: W B Glenn<BR>Born: 19 Jun 1862<BR>Died: 29 Jul 1929<BR>', 'image': 'pond_springs_0065.png'},
  {'start': '29 May 1905','title': 'W M Chapman', 'description': 'Name: W M Chapman<BR>Born: 8 May 1826<BR>Died: 29 May 1905<BR>', 'image': 'pond_springs_0060.png'},
  {'start': '29 Oct 1934','title': 'Claude Dennis Hartson', 'description': 'Name: Claude Dennis Hartson<BR>Born: 27 Jun 1882<BR>Died: 29 Oct 1934<BR>'},
  {'start': '03 Feb 1907','title': 'Mollie Lee', 'description': 'Name: Mollie Lee<BR>Born: 14 Oct 1864<BR>Died: 3 Feb 1907<BR>', 'image': 'pond_springs_0003.png'},
  {'start': '03 Jan 1931','title': 'Blanche Marie Davis', 'description': 'Name: Blanche Marie Davis<BR>Born: 23 Oct 1917<BR>Died: 3 Jan 1931<BR>Note: no stone, info from the 1964 transcription<BR>'},
  {'start': '03 Jun 1920','title': 'Cora Blanche Warren', 'description': 'Name: Cora Blanche Warren<BR>Born: 23 Mar 1916<BR>Died: 3 Jun 1920<BR>Note: dau of William Oscar Warren and Cora Agnes Glenn<BR>'},
  {'start': '03 Oct 1877','title': 'William Thomas Walden', 'description': 'Name: William Thomas Walden<BR>Born: 7 Mar 1877<BR>Died: 3 Oct 1877<BR>Marker Text: son of J.A. and M.F. Walden<BR>'},
  {'start': '03 Oct 1885','title': 'William P Buttery', 'description': 'Name: William P Buttery<BR>Born: [1811]<BR>Died: 3 Oct 1885<BR>Marker Text: Age 74 years<BR>', 'image': 'pond_springs_0020.png'},
  {'start': '03 Sep 1939','title': 'William D[avid] Walden', 'description': 'Name: William D[avid] Walden<BR>Born: 11 Oct 1859<BR>Died: 3 Sep 1939<BR>Note: son of Thomas Hughell Walden and Rachel Hays<BR>'},
  {'start': '30 Jun 1902','title': 'L[ouise] A[ntoinette] Petri', 'description': 'Name: L[ouise] A[ntoinette] Petri<BR>Born: 5 Nov 1877<BR>Died: 30 Jun 1902<BR>Marker Text: our beloved daughter and sister<BR>Note: "L.A.P" only, remainder from the 1964 transcription<BR>', 'image': 'pond_springs_0072.png'},
  {'start': '30 Mar 1869','title': 'Polly M Gault', 'description': 'Name: Polly M Gault<BR>Born: 22 Sep 1845<BR>Died: 30 Mar 1869<BR>Marker Text: consort of R.T. Gault<BR>', 'image': 'pond_springs_0018.png'},
  {'start': '30 Mar 1913','title': 'Jesse O Lee', 'description': 'Name: Jesse O Lee<BR>Born: 7 Jun 1877<BR>Died: 30 Mar 1913<BR>Note: Woodmen of the World<BR>', 'image': 'pond_springs_0066.png'},
  {'start': '30 May 1927','title': 'W H Cunningham', 'description': 'Name: W H Cunningham<BR>Born: 18 Jul 1915<BR>Died: 30 May 1927<BR>'},
  {'start': '31 Dec 1932','title': 'Vernon Richards', 'description': 'Name: Vernon Richards<BR>Born: 31 Dec 1932<BR>Died: 31 Dec 1932<BR>Marker Text: twins<BR>Note: s/w Lavern<BR>'},
  {'start': '04 Aug 1869','title': 'Susan E Gault', 'description': 'Name: Susan E Gault<BR>Born: 30 Dec 1868<BR>Died: 4 Aug 1869<BR>'},
  {'start': '04 Jan 1933','title': 'Lavern Richards', 'description': 'Name: Lavern Richards<BR>Born: 31 Dec 1932<BR>Died: 4 Jan 1933<BR>Marker Text: twins<BR>Note: s/w Vernon<BR>'},
  {'start': '05 Apr 1883','title': 'James S Jackson', 'description': 'Name: James S Jackson<BR>Born: 1883<BR>Died: 5 Apr 1883<BR>', 'image': 'pond_springs_0027.png'},
  {'start': '05 Dec 1883','title': 'Nancy Stewart', 'description': 'Name: Nancy Stewart<BR>Born: 3 Jun 1806<BR>Died: 5 Dec 1883<BR>Marker Text: wife of Laban Stewart<BR>Note: stone broken<BR>', 'image': 'pond_springs_0035.png'},
  {'start': '05 Oct 1935','title': 'Annie May Hammack', 'description': 'Name: Annie May Hammack<BR>Born: 30 May 1881<BR>Died: 5 Oct 1935<BR>'},
  {'start': '06 Jan 1929','title': 'Lavina Ann Chapman', 'description': 'Name: Lavina Ann Chapman<BR>Born: 5 Oct 1844<BR>Died: 6 Jan 1929<BR>Note: "Lavinia Hyland Chapman" according to the historical marker<BR>'},
  {'start': '06 May 1928','title': 'Clara Edna Walden', 'description': 'Name: Clara Edna Walden<BR>Born: 17 Sep 1923<BR>Died: 6 May 1928<BR>'},
  {'start': '06 May 1966','title': 'Willie J. Nelson', 'description': 'Name: Willie J. Nelson<BR>Born: 13 May 1906<BR>Died: 6 May 1966<BR>Note: a mason<BR>', 'image': 'pond_springs_0078.png'},
  {'start': '06 Oct 1902','title': 'John Richard Ward', 'description': 'Name: John Richard Ward<BR>Born: 6 Oct 1902<BR>Died: 6 Oct 1902<BR>Marker Text: son of J.R. and E.L. Ward<BR>Note: s/w Pinkie son of Jacob/Jaster Robert Ward and Ellen Louise King<BR>', 'image': 'pond_springs_0053.png'},
  {'start': '07 Apr 1977','title': 'Vera Hunter Nelson', 'description': 'Name: Vera Hunter Nelson<BR>Born: 8 Sep 1903<BR>Died: 7 Apr 1977<BR>', 'image': 'pond_springs_0079.png'},
  {'start': '07 Aug 1909','title': 'George E Long', 'description': 'Name: George E Long<BR>Born: 9 Jan 1887<BR>Died: 7 Aug 1909<BR>Note: son of William Long and Willie Ann Oliver, d. of typhoid<BR>', 'image': 'pond_springs_0091.png'},
  {'start': '07 Jan 1923','title': 'Annie Franklin', 'description': 'Name: Annie Franklin<BR>Born: 17 May 1850<BR>Died: 7 Jan 1923<BR>Marker Text: wife of John Franklin<BR>'},
  {'start': '07 Mar 1920','title': 'Hiram Hartson', 'description': 'Name: Hiram Hartson<BR>Born: 27 Jul 1855<BR>Died: 7 Mar 1920<BR>Marker Text: father of 5 children, 3 girls and 2 boys<BR>Note: husband of Mary Alice hartson<BR>'},
  {'start': '07 Sep 1908','title': 'J[ames] M[adison] Ennis', 'description': 'Name: J[ames] M[adison] Ennis<BR>Born: 22 Mar 1848<BR>Died: 7 Sep 1908<BR>Note: no stone, info from the 1964 transcription, husband of Nancy J. Ennis<BR>'},
  {'start': '08 Dec 1946','title': 'William Horace Warren', 'description': 'Name: William Horace Warren<BR>Born: 1 Apr 1912<BR>Died: 8 Dec 1946<BR>Marker Text: Texas, PFC Trans Corps WWII<BR>Note: son of William Oscar Warren and Cora Agnes Glenn<BR>'},
  {'start': '08 Jun 1871','title': 'Elizabeth King', 'description': 'Name: Elizabeth King<BR>Born: 15 Dec 1815<BR>Died: 8 Jun 1871<BR>Marker Text: consort of W.A. King<BR>', 'image': 'pond_springs_0019.png'},
  {'start': '08 Mar 1882','title': 'W.H. Brooks', 'description': 'Name: W.H. Brooks<BR>Born: 29 Nov 1858<BR>Died: 8 Mar 1882<BR>Note: footstone only, info from the 1964 transcription<BR>', 'image': 'pond_springs_0044.png'},
  {'start': '08 Nov 1886','title': 'S J Rhodes', 'description': 'Name: S J Rhodes<BR>Born: 1 Apr 1859<BR>Died: 8 Nov 1886<BR>Marker Text: wife of J.L. Rhodes<BR>Note: "S.J.R." only, remainder from the 1964 transcription<BR>', 'image': 'pond_springs_0045.png'},
  {'start': '08 Oct 1920','title': 'Lola Avidevdo', 'description': 'Name: Lola Avidevdo<BR>Born: <BR>Died: 8 Oct 1920<BR>Marker Text: dau of Demitrio Avidevdo and ?? Nesterio<BR>Note: no stone, info from the Williamson County [Tx] Death Records, Book 2<BR>'},
  {'start': '09 Feb 1926','title': 'Sally E Smith', 'description': 'Name: Sally E Smith<BR>Born: 8 Dec 1841<BR>Died: 9 Feb 1926<BR>', 'image': 'pond_springs_0008.png'},
  {'start': '09 Jun 1878','title': 'Elizabeth Booker', 'description': 'Name: Elizabeth Booker<BR>Born: 28 Oct 1843<BR>Died: 9 Jun 1878<BR>Marker Text: wife of T.H. Booker<BR>Note: badly eroded<BR>', 'image': 'pond_springs_0014.png'},
  {'start': '09 Mar 1896','title': 'W. S. Heaton', 'description': 'Name: W. S. Heaton<BR>Born: 29 Mar 1844<BR>Died: 9 Mar 1896<BR>Note: s/w Martha J. Heaton<BR>', 'image': 'pond_springs_0009.png'},
  {'start': '11 Apr 1936','title': 'Andrew Jackson Shannon', 'description': 'Name: Andrew Jackson Shannon<BR>Born: 4 Jan 1901<BR>Died: Apr 11 1936<BR>Note: husband of _____ Mouser, son of James and Aslee Shannon<BR>', 'image': 'pond_springs_0049.png'},
  {'start': '01 Jan 1957','title': 'Jesse Garcia', 'description': 'Name: Jesse Garcia<BR>Born: <BR>Died: Jan 1957<BR>Note: Cook funeral home<BR>', 'image': 'pond_springs_0024.png'},
  {'start': '01 Jun 1909','title': 'James T[homas] Rutledge', 'description': 'Name: James T[homas] Rutledge<BR>Born: Sep 1851<BR>Died: Jun 1909<BR>Note: s/w Mary E. Rutledge, son of Edward Armstrong Rutledge and Mary Francis young<BR>', 'image': 'pond_springs_0001.png'},
  {'start': '01 Jun 1954','title': 'John A Cantwell', 'description': 'Name: John A Cantwell<BR>Born: 1877<BR>Died: Jun 1954<BR>Note: s/w Sarah E. Cantwell<BR>', 'image': 'pond_springs_0022.png'},
  {'start': '01 Jun 1958','title': 'Fora A Cantwell', 'description': 'Name: Fora A Cantwell<BR>Born: <BR>Died: Jun 1958<BR>Marker Text: "Mr."<BR>'},
  {'start': '01 Mar 1927','title': 'Mary E[stella] Rutledge', 'description': 'Name: Mary E[stella] Rutledge<BR>Born: Oct 1851<BR>Died: Mar 1927<BR>Note: s/w James T. Rutledge, dau of Francis M. Buchanan and Nancy Ann _____<BR>', 'image': 'pond_springs_0001.png'},
  {'start': '01 Mar 1936','title': 'Aslee Shannon', 'description': 'Name: Aslee Shannon<BR>Born: 16 Feb 1868<BR>Died: Mar 1936<BR>Note: wife of James<BR>', 'image': 'pond_springs_0048.png'},
  {'start': '01 Oct 1881','title': 'Green McClure', 'description': 'Name: Green McClure<BR>Born: 24 Nov 1837<BR>Died: Oct 1881<BR>Note: husband of Nancy, a mason<BR>', 'image': 'pond_springs_0037.png'}
]
}
