{
'dateTimeForamt': 'iso8601',
'events': [

  {'start': '01 Jan 1965','title': 'John Willey', 'description': 'Name: John Willey<BR>Born: <BR>Died: 1 Jan 1965<BR>Marker Text: [paper under glass in concrete]<BR>'},
  {'start': '10 Apr 1922','title': 'Louisa Ake', 'description': 'Name: Louisa Ake<BR>Born: 10 Feb 1867<BR>Died: 10 Apr 1922<BR>Marker Text: [s/w John]<BR>'},
  {'start': '10 Jun 1922','title': 'Maggie Plummer', 'description': 'Name: Maggie Plummer<BR>Born: <BR>Died: 10 Jun 1922<BR>Marker Text: Age 76 [s/w Willie Wray; concrete]<BR>'},
  {'start': '11 Jan 1972','title': 'Greeley Harris', 'description': 'Name: Greeley Harris<BR>Born: 2 Apr 1894<BR>Died: 11 Jan 1972<BR>Marker Text: TX PVT US Army WWI<BR>'},
  {'start': '12 Apr 1921','title': 'Ruth Mae Akes', 'description': 'Name: Ruth Mae Akes<BR>Born: <BR>Died: 12 Apr 1921<BR>Marker Text: Age 6 mos<BR>'},
  {'start': '12 Aug 1909','title': 'Charles Langham', 'description': 'Name: Charles Langham<BR>Born: 4 Jun 1842<BR>Died: 12 Aug 1909<BR>Marker Text: [concrete]<BR>'},
  {'start': '14 Apr 1963','title': 'Emma Conaway', 'description': 'Name: Emma Conaway<BR>Born: 1 Sep 1894<BR>Died: 14 Apr 1963<BR>'},
  {'start': '15 Jan 1918','title': 'Oliver Lee Latson', 'description': 'Name: Oliver Lee Latson<BR>Born: <BR>Died: 15 Jan 1918<BR>Marker Text: Age 5 mos [concrete]<BR>'},
  {'start': '16 Aug 1919','title': 'John Jennings', 'description': 'Name: John Jennings<BR>Born: <BR>Died: 16 Aug 1919<BR>Marker Text: Age 74 [s/w Willie Akes; concrete]<BR>'},
  {'start': '16 May 1983','title': 'Kinney Crayton', 'description': 'Name: Kinney Crayton<BR>Born: 5 Sep 1895<BR>Died: 16 May 1983<BR>Marker Text: US Army WWI<BR>'},
  {'start': '17 Jan 1981','title': 'Melton Bruto Berr', 'description': 'Name: Melton Bruto Berr<BR>Born: 5 Jan 1965<BR>Died: 17 Jan 1981<BR>Marker Text: [concrete]<BR>'},
  {'start': '18 Aug 1928','title': 'John Ake', 'description': 'Name: John Ake<BR>Born: 1 Nov 1855<BR>Died: 18 Aug 1928<BR>Marker Text: [s/w Louisa]<BR>'},
  {'start': '18 Jan 1919','title': 'Willie Akes', 'description': 'Name: Willie Akes<BR>Born: <BR>Died: 18 Jan 1919<BR>Marker Text: Age 28 [s/w John Jennings; concrete]<BR>'},
  {'start': '31 Dec 1956','title': 'Sam Fisher', 'description': 'Name: Sam Fisher<BR>Born: 1871<BR>Died: 1956<BR>Marker Text: [broken funeral plate, loose in bush stump]<BR>'},
  {'start': '02 Mar 1902','title': 'Bettie Hardin', 'description': 'Name: Bettie Hardin<BR>Born: <BR>Died: 2 Mar 1902<BR>Marker Text: Age 60 [concrete, leaning on fence]<BR>'},
  {'start': '02 Nov 1918','title': 'Willie Wray', 'description': 'Name: Willie Wray<BR>Born: <BR>Died: 2 Nov 1918<BR>Marker Text: Age 27 [s/w Maggie Plummer; concrete]<BR>'},
  {'start': '20 Sep 1957','title': 'Myrtle Boulding', 'description': 'Name: Myrtle Boulding<BR>Born: 14 Oct 1863<BR>Died: 20 Sep 1957<BR>'},
  {'start': '20 Sep 1958','title': 'Issac Joe Fresch', 'description': 'Name: Issac Joe Fresch<BR>Born: 18 Sep 1879<BR>Died: 20 Sep 1958<BR>Marker Text: Husband<BR>'},
  {'start': '23 Jul 1983','title': 'Willie L Boulding', 'description': 'Name: Willie L Boulding<BR>Born: 6 Feb 1927<BR>Died: 23 Jul 1983<BR>Marker Text: PVT US Army WWII<BR>'},
  {'start': '24 Dec 1989','title': 'Roxie Ann Wilkins', 'description': 'Name: Roxie Ann Wilkins<BR>Born: 13 Dec 1952<BR>Died: 24 Dec 1989<BR>'},
  {'start': '24 Nov 1984','title': 'Vina Wiley Edwards', 'description': 'Name: Vina Wiley Edwards<BR>Born: 27 Sep 1899<BR>Died: 24 Nov 1984<BR>'},
  {'start': '25 Jan 1925','title': 'Mary Langham', 'description': 'Name: Mrs Mary Langham<BR>Born: <BR>Died: 25 Jan 1925<BR>'},
  {'start': '25 Mar 1969','title': 'Myrtle G Fresch', 'description': 'Name: Myrtle G Fresch<BR>Born: 10 Jun 1889<BR>Died: 25 Mar 1969<BR>Marker Text: Wife<BR>'},
  {'start': '25 Sep 1960','title': 'Louis T Boulding', 'description': 'Name: Louis T Boulding<BR>Born: 24 Sep 1889<BR>Died: 25 Sep 1960<BR>Marker Text: TX CPL US Army WWI<BR>'},
  {'start': '26 Aug 1976','title': 'James B Reeves', 'description': 'Name: James B Reeves<BR>Born: 9 Aug 1912<BR>Died: 26 Aug 1976<BR>Marker Text: SSgt US Army WWII<BR>'},
  {'start': '28 Feb 1968','title': 'Willie B Miller', 'description': 'Name: Willie B Miller<BR>Born: 20 Feb 1897<BR>Died: 28 Feb 1968<BR>'},
  {'start': '28 May 1910','title': 'Caroline Niel', 'description': 'Name: Caroline Niel<BR>Born: <BR>Died: 28 May 1910<BR>Marker Text: Age 96, [s/w Adan Newels; concrete]<BR>'},
  {'start': '04 Nov 1907','title': 'Maria Langham', 'description': 'Name: Maria Langham<BR>Born: 17 Jun 1873<BR>Died: 4 Nov 1907<BR>'},
  {'start': '05 Mar 1967','title': 'Nancy Brown', 'description': 'Name: Mrs Nancy Brown<BR>Born: 12 Dec 1873<BR>Died: 5 Mar 1967<BR>Marker Text: [paper under glass set in concrete]<BR>'},
  {'start': '06 Jan 1911','title': 'Adan Newels', 'description': 'Name: Adan Newels<BR>Born: <BR>Died: 6 Jan 1911<BR>Marker Text: Age 87 [s/w Caroline Niel; concrete]<BR>'},
  {'start': '08 Aug 1959','title': 'I D Washington', 'description': 'Name: I D Washington<BR>Born: 8 Jul 1893<BR>Died: 8 Aug 1959<BR>Marker Text: TX PFC US Army WWI<BR>'},
  {'start': '08 Jul 1975','title': 'Alice Edwards', 'description': 'Name: Alice Edwards<BR>Born: 28 Mar 1896<BR>Died: 8 Jul 1975<BR>Marker Text: US Army WWI<BR>'},
  {'start': '08 May 1951','title': 'Emma Line Griffin', 'description': 'Name: Mrs Emma Line Griffin<BR>Born: 6 Jun 1866<BR>Died: 8 May 1951<BR>Marker Text: Hutto Tx [paper under glass set in concrete]<BR>'},
  {'start': '09 Jun 2001','title': 'Robert McKenzie', 'description': 'Name: Robert McKenzie<BR>Born: 22 Jul 1928<BR>Died: 9 Jun 2001<BR>Marker Text: Age 72 [paper under glass]<BR>'}
]
}
