{
'dateTimeForamt': 'iso8601',
'events': [

  {'start': '01 Apr 1982','title': 'Waymon Dewitt Stockton', 'description': 'Name: Waymon Dewitt Stockton<BR>Born: 24 Sep 1911<BR>Died: 1 Apr 1982<BR>Note: s/w Katie; marker 17 on map<BR>'},
  {'start': '01 Feb 1972','title': 'Johnnye Dee Perry', 'description': 'Name: Johnnye Dee Perry<BR>Born: 16 Jan 1907<BR>Died: 1 Feb 1972<BR>Note: s/w Milton; marker 7 on map<BR>'},
  {'start': '10 Sep 1979','title': 'Douglas H Connell', 'description': 'Name: Douglas H Connell Sr<BR>Born: 5 Feb 1899<BR>Died: 10 Sep 1979<BR>Marker Text: S2 US Navy WWI<BR>Note: s/w Billie; marker 91 on map<BR>'},
  {'start': '11 Jul 1981','title': 'Billie H Connell', 'description': 'Name: Billie H Connell<BR>Born: 22 Dec 1904<BR>Died: 11 Jul 1981<BR>Marker Text: Mg 18 Dec 1923<BR>Note: s/w Douglas; marker 92 on map<BR>'},
  {'start': '11 Sep 1992','title': 'Betty Tolin Perry', 'description': 'Name: Betty Tolin Perry<BR>Born: 11 Feb 1918<BR>Died: 11 Sep 1992<BR>Marker Text: Mg 13 Mar 1943<BR>Note: s/w Thomas; marker 21 on map<BR>'},
  {'start': '12 Apr 1899','title': 'James Leo Crothers', 'description': 'Name: James Leo Crothers<BR>Born: <BR>Died: 12 Apr 1899<BR>Marker Text: Age 18mos?; son of W.F. & Emily Crothers<BR>Note: marker 53 on map<BR>'},
  {'start': '12 Feb 1953','title': 'Warren Fay Crothers', 'description': 'Name: Warren Fay Crothers<BR>Born: 22 Jan 1872<BR>Died: 12 Feb 1953<BR>Note: s/w Emily; marker 54 on map<BR>', 'image': 'stockton_0055.jpg'},
  {'start': '13 Apr 1918','title': 'Infant Stockton', 'description': 'Name: Infant Stockton<BR>Born: 18 Dec 1907<BR>Died: 13 Apr 1918<BR>Marker Text: Infant son of W.B. & M. Stockton<BR>Note: marker 66 on map<BR>'},
  {'start': '13 Dec 1921','title': 'E. M Perry', 'description': 'Name: E. M Perry<BR>Born: 25 Jan 1853<BR>Died: 13 Dec 1921<BR>Note: s/w Augusta; marker 30 on map<BR>'},
  {'start': '13 Feb 2002','title': 'Charles Malcolm Ellison', 'description': 'Name: Charles Malcolm Ellison<BR>Born: 27 Nov 1945<BR>Died: 13 Feb 2002<BR>Note: marker 78 on map<BR>'},
  {'start': '13 Jul 1984','title': 'Ira Aten Connell', 'description': 'Name: Ira Aten Connell<BR>Born: 17 May 1904<BR>Died: 13 Jul 1984<BR>Note: s/w Irene; marker 76 on map<BR>', 'image': 'stockton_0077.jpg'},
  {'start': '13 Oct 1891','title': 'Augusta Mabel Perry', 'description': 'Name: Augusta Mabel Perry<BR>Born: 27 Jul 1862<BR>Died: 13 Oct 1891<BR>Note: s/w E. M.; marker 31 on map<BR>'},
  {'start': '14 Feb 1929','title': 'Augusta P Stockton', 'description': 'Name: Augusta P Stockton<BR>Born: 6 Apr 1925<BR>Died: 14 Feb 1929<BR>Note: marker 63 on map<BR>'},
  {'start': '14 Oct 1921','title': 'Mozelle Stockton Hardy Calvery', 'description': 'Name: Mozelle Stockton Hardy Calvery<BR>Born: <BR>Died: 14 Oct 1921<BR>Note: marker 84 on map<BR>'},
  {'start': '14 Sep 1919','title': 'Bessie White Stockton', 'description': 'Name: Bessie White Stockton<BR>Born: 18 Jul 1894<BR>Died: 14 Sep 1919<BR>Note: s/w Hugh; marker 56 on map<BR>'},
  {'start': '14 Sep 1919','title': 'Hugh McIntyre Stockton', 'description': 'Name: Hugh McIntyre Stockton<BR>Born: 22 Feb 1883<BR>Died: 14 Sep 1919<BR>Note: s/w Bessie; marker 57 on map<BR>'},
  {'start': '14 Sep 1919','title': 'Mary Elizabeth Stockton', 'description': 'Name: Mary Elizabeth Stockton<BR>Born: 2 Jun 1916<BR>Died: 14 Sep 1919<BR>Note: s/w Lois; marker 58 on map<BR>'},
  {'start': '14 Sep 1935','title': 'Johnny M Stockton', 'description': 'Name: Johnny M Stockton<BR>Born: 14 sep 1929<BR>Died: 14 Sep 1935<BR>Note: marker 64 on map<BR>'},
  {'start': '15 Mar 1992','title': 'Douglas H Connell', 'description': 'Name: Douglas H Connell Jr<BR>Born: 24 Jul 1925<BR>Died: 15 Mar 1992<BR>Marker Text: Pfc USMC WWII<BR>Note: marker 75 on map<BR>'},
  {'start': '15 Sep 1920','title': 'D. H. Stockton', 'description': 'Name: D. H. Stockton<BR>Born: 7 Sep 1836<BR>Died: 15 Sep 1920<BR>Note: s/w Mary; marker 35 on map<BR>', 'image': 'stockton_0036.jpg'},
  {'start': '16 Jan 1982','title': 'Anna Mae Stockton', 'description': 'Name: Anna Mae Stockton<BR>Born: 17 Jan 1942<BR>Died: 16 Jan 1982<BR>Note: marker 19 on map<BR>'},
  {'start': '16 May 1916','title': 'Mary E Stockton', 'description': 'Name: Mary E Stockton<BR>Born: 3 Dec 1842<BR>Died: 16 May 1916<BR>Marker Text: Wife of D.H. Stockton<BR>Note: s/w D.H.; marker 36 on map<BR>', 'image': 'stockton_0036.jpg'},
  {'start': '16 May 1998','title': 'Mary Perry House', 'description': 'Name: Mary Perry House<BR>Born: 3 Sep 1952<BR>Died: 16 May 1998<BR>Note: marker 22 on map<BR>'},
  {'start': '16 Oct 1891','title': 'Mary Belle Perry', 'description': 'Name: Mary Belle Perry<BR>Born: 16 Dec 1882<BR>Died: 16 Oct 1891<BR>Note: marker 29 on map<BR>'},
  {'start': '16 Oct 1963','title': 'Douglas Hayden Perry', 'description': 'Name: Douglas Hayden Perry<BR>Born: 20 Nov 1890<BR>Died: 16 Oct 1963<BR>Note: s/w Mary; marker 27 on map<BR>'},
  {'start': '17 Jan 1926','title': 'Bill Connell', 'description': 'Name: Bill Connell<BR>Born: <BR>Died: 17 Jan 1926<BR>Marker Text: Son of Irene & Ira Connell<BR>Note: marker 52 on map<BR>'},
  {'start': '17 Mar 1899','title': 'James A Stockton', 'description': 'Name: James A Stockton<BR>Born: <BR>Died: 17 Mar 1899<BR>Marker Text: Age 33y 1m 19d<BR>Note: marker 33 on map<BR>'},
  {'start': '18 Aug 1906','title': 'M. Elizabeth Connell', 'description': 'Name: M. Elizabeth Connell<BR>Born: 31 Aug 1897<BR>Died: 18 Aug 1906<BR>Marker Text: Daughter of E.F. & Sophia Connell<BR>Note: marker 50 on map<BR>'},
  {'start': '18 Mar 1912','title': 'E.F. Connell', 'description': 'Name: E.F. Connell Jr<BR>Born: 17 May 1906<BR>Died: 18 Mar 1912<BR>Note: marker 51 on map<BR>'},
  {'start': '19 Jun 1940','title': 'Edward Fulton Connell', 'description': 'Name: Edward Fulton Connell<BR>Born: 17 May 1863<BR>Died: 19 Jun 1940<BR>Marker Text: Texas Ranger 1892-1896<BR>Note: s/w Sophia; marker 49 on map<BR>'},
  {'start': '19 Mar 1981','title': 'Mattie M Stockton', 'description': 'Name: Mattie M Stockton<BR>Born: 26 Jan 1885<BR>Died: 19 Mar 1981<BR>Note: marker 74 on map<BR>'},
  {'start': '19 Nov 2006','title': 'Helen Rimmer Storey', 'description': 'Name: Helen Rimmer Storey<BR>Born: 12 Oct 1915<BR>Died: 19 Nov 2006<BR>Note: marker 98 on map<BR>'},
  {'start': '31 Dec 1913','title': 'Joseph Hayden Knight', 'description': 'Name: Joseph Hayden Knight<BR>Born: 1905<BR>Died: 1913<BR>Note: marker 39 on map<BR>'},
  {'start': '31 Dec 1928','title': 'Fannie Talbot Stockton', 'description': 'Name: Fannie Talbot Stockton<BR>Born: 1849<BR>Died: 1928<BR>Note: marker 34 on map<BR>'},
  {'start': '31 Dec 1931','title': 'Douglas Hayden Stockton', 'description': 'Name: Douglas Hayden Stockton Jr<BR>Born: 1876<BR>Died: 1931<BR>Note: s/w Myrtle; marker 4 on map<BR>'},
  {'start': '31 Dec 1931','title': 'Dee Thomas Stockton', 'description': 'Name: Dee Thomas Stockton<BR>Born: 1867<BR>Died: 1931<BR>Marker Text: Father<BR>Note: marker 16 on map<BR>'},
  {'start': '31 Dec 1935','title': 'A. W. Stockton', 'description': 'Name: A. W. Stockton<BR>Born: 1869<BR>Died: 1935<BR>Note: marker 71 on map<BR>', 'image': 'stockton_0071.jpg'},
  {'start': '31 Dec 1939','title': 'Guy S Perry', 'description': 'Name: Guy S Perry<BR>Born: 1887<BR>Died: 1939<BR>Note: marker 8 on map<BR>'},
  {'start': '31 Dec 1941','title': 'Myrtle E Stockton', 'description': 'Name: Myrtle E Stockton<BR>Born: 1878<BR>Died: 1941<BR>Note: s/w Douglas; marker 5 on map<BR>'},
  {'start': '31 Dec 1947','title': 'Martha Stockton Ford', 'description': 'Name: Martha Stockton Ford<BR>Born: 1864<BR>Died: 1947<BR>Note: marker 3 on map<BR>'},
  {'start': '31 Dec 1951','title': 'Sim[eon] C[arothers] Stockton', 'description': 'Name: Sim[eon] C[arothers] Stockton<BR>Born: 1912<BR>Died: 1951<BR>Marker Text: Father<BR>Note: marker 87 on map<BR>'},
  {'start': '31 Dec 1953','title': 'Andy Stockton Knight', 'description': 'Name: Andy Stockton Knight<BR>Born: 1916<BR>Died: 1953<BR>Note: marker 40 on map<BR>'},
  {'start': '31 Dec 1955','title': 'Mary Ann Hardy', 'description': 'Name: Mary Ann Hardy<BR>Born: <BR>Died: 1955<BR>Marker Text: infant<BR>Note: marker 82 on map<BR>'},
  {'start': '31 Dec 1958','title': 'Lomelea Bridges', 'description': 'Name: Lomelea Bridges<BR>Born: 1940<BR>Died: 1958<BR>Marker Text: Daughter<BR>Note: marker 88 on map<BR>'},
  {'start': '31 Dec 1962','title': 'Dee Thomas Stockton', 'description': 'Name: Dee Thomas Stockton (Jr.)<BR>Born: 1894<BR>Died: 1962<BR>Marker Text: Mg 9 Apr 1916<BR>Note: s/w Emma; marker 44 on map<BR>'},
  {'start': '31 Dec 1964','title': 'Roy B Stockton', 'description': 'Name: Roy B Stockton<BR>Born: 1905<BR>Died: 1964<BR>Marker Text: Daddy<BR>Note: marker 85 on map<BR>'},
  {'start': '31 Dec 1967','title': 'Ada Stockton Knight', 'description': 'Name: Ada Stockton Knight<BR>Born: 1885<BR>Died: 1967<BR>Note: s/w Jim; marker 37 on map<BR>'},
  {'start': '31 Dec 1968','title': 'Jim Kuykendall Knight', 'description': 'Name: Jim Kuykendall Knight<BR>Born: 1881<BR>Died: 1968<BR>Note: s/w Ada; marker 38 on map<BR>'},
  {'start': '31 Dec 1980','title': 'S. Autrey Bridges', 'description': 'Name: S. Autrey Bridges<BR>Born: 1901<BR>Died: 1980<BR>Note: s/w Myrtle; marker 89 on map<BR>'},
  {'start': '31 Dec 1980','title': 'Richard H. Knight', 'description': 'Name: Richard H. Knight<BR>Born: 1940<BR>Died: 1980<BR>Marker Text: U.S. Navy<BR>Note: marker 79 on map<BR>'},
  {'start': '31 Dec 1981','title': 'Billy C Hardy', 'description': 'Name: Billy C Hardy<BR>Born: 1933<BR>Died: 1981<BR>Marker Text: US Army Korea<BR>Note: marker 83 on map<BR>'},
  {'start': '31 Dec 1986','title': 'Vonelle Stockton Powitzsky', 'description': 'Name: Vonelle Stockton Powitzsky<BR>Born: 1912<BR>Died: 1986<BR>Marker Text: Mamma<BR>Note: marker 86 on map<BR>'},
  {'start': '31 Dec 1995','title': 'Elizabeth Knight Bingham', 'description': 'Name: Elizabeth Knight Bingham<BR>Born: 1910<BR>Died: 1995<BR>Note: marker 60 on map<BR>'},
  {'start': '02 Dec 1925','title': 'Edith L Stockton', 'description': 'Name: Edith L Stockton<BR>Born: 2 Oct 1923<BR>Died: 2 Dec 1925<BR>'},
  {'start': '20 Apr 1890','title': 'S. C. Stockton', 'description': 'Name: S. C. Stockton<BR>Born: 7 Oct 1874<BR>Died: 20 Apr 1890<BR>Marker Text: Age 15y 6m 13d<BR>Note: marker 32 on map<BR>'},
  {'start': '20 Mar 1962','title': 'James Kirk Knight', 'description': 'Name: James Kirk Knight Jr<BR>Born: 14 Jun 1908<BR>Died: 20 Mar 1962<BR>Note: s/w Margie; marker 41 on map<BR>'},
  {'start': '31 Dec 2000','title': 'Emma Sappington Stockton', 'description': 'Name: Emma Sappington Stockton<BR>Born: 1899<BR>Died: 2000<BR>Note: s/w Dee; marker 43 on map<BR>'},
  {'start': '21 Aug 1916','title': 'Fred Stockton', 'description': 'Name: Fred Stockton<BR>Born: 18 Aug 1915<BR>Died: 21 Aug 1916<BR>Marker Text: Baby son of W.B. & M. Stockton<BR>Note: marker 65 on map<BR>'},
  {'start': '22 Dec 2005','title': 'Mark Douglas Stockton', 'description': 'Name: Mark Douglas Stockton<BR>Born: 7 Jun 1961<BR>Died: 22 Dec 2005<BR>Note: marker 80 on map<BR>'},
  {'start': '22 Feb 2009','title': 'Frank T Zitzo', 'description': 'Name: Frank T Zitzo<BR>Born: 8 Apr 1927<BR>Died: 22 Feb 2009<BR>Marker Text: USNR<BR>Note: marker 93 on map<BR>'},
  {'start': '22 Jun 1918','title': 'Edna Irene Stockton', 'description': 'Name: Edna Irene Stockton<BR>Born: 8 Jan 1917<BR>Died: 22 Jun 1918<BR>Marker Text: Daughter of Tom & Edna Stockton<BR>Note: marker 47 on map<BR>'},
  {'start': '23 Mar 1967','title': 'Geo. M Connell', 'description': 'Name: Geo. M Connell<BR>Born: 8 Aug 1907<BR>Died: 23 Mar 1967<BR>Note: marker 69 on map<BR>', 'image': 'stockton_0069.jpg'},
  {'start': '25 Apr 1995','title': 'Lee O Stockton', 'description': 'Name: Lee O Stockton<BR>Born: 13 Sep 1918<BR>Died: 25 Apr 1995<BR>Marker Text: S1 US Navy WWII<BR>Note: marker 97 on map<BR>'},
  {'start': '26 Feb 1921','title': 'H.M. Stockton', 'description': 'Name: H.M. Stockton<BR>Born: 2 Aug 1909<BR>Died: 26 Feb 1921<BR>Marker Text: Son of Mr. & Mrs. D.T. Stockton<BR>Note: marker 14 on map<BR>'},
  {'start': '26 Jun 1984','title': 'Mary Dulce Perry', 'description': 'Name: Mary Dulce Perry<BR>Born: 26 Jul 1894<BR>Died: 26 Jun 1984<BR>Note: s/w Douglas; marker 28 on map<BR>'},
  {'start': '26 Oct 1907','title': 'Fannie Price Stockton', 'description': 'Name: Fannie Price Stockton<BR>Born: <BR>Died: 26 Oct 1907<BR>Marker Text: Age 38y 4m 9d; wife of D.T. Stockton<BR>Note: marker 46 on map<BR>'},
  {'start': '28 Jul 1928','title': 'Emma L Stockton', 'description': 'Name: Emma L Stockton<BR>Born: 11 Nov 1927<BR>Died: 28 Jul 1928<BR>Note: marker 62 on map<BR>'},
  {'start': '28 Nov 1981','title': 'C. Weldon Bentley', 'description': 'Name: C. Weldon Bentley<BR>Born: 6 Oct 1908<BR>Died: 28 Nov 1981<BR>Note: s/w Laura; marker 10 on map<BR>'},
  {'start': '29 Nov 1910','title': 'Ead White', 'description': 'Name: Ead White<BR>Born: <BR>Died: 29 Nov 1910<BR>Marker Text: Age 80y; Colored slave Nurse of Mrs. D.H. Stockton<BR>Note: marker 72 on map<BR>'},
  {'start': '03 Jan 1977','title': 'Irene Crothers Loy', 'description': 'Name: Irene Crothers Loy<BR>Born: 15 Sep 1895<BR>Died: 3 Jan 1977<BR>Note: marker 59 on map<BR>'},
  {'start': '03 Mar 1989','title': 'Edna Belle Perry Newton', 'description': 'Name: Edna Belle Perry Newton<BR>Born: 16 Apr 1919<BR>Died: 3 Mar 1989<BR>Note: s/w Harris; marker 26 on map<BR>'},
  {'start': '03 Mar 2003','title': 'Haden Price Stockton', 'description': 'Name: Haden Price Stockton<BR>Born: 7 Apr 1920<BR>Died: 3 Mar 2003<BR>Marker Text: CPO, U.S. Navy, WWII<BR>Note: marker 61 on map<BR>'},
  {'start': '30 Dec 1985','title': 'Lulu Connell Bennett', 'description': 'Name: Lulu Connell Bennett<BR>Born: 5 Jul 1909<BR>Died: 30 Dec 1985<BR>Marker Text: Beloved aunt<BR>Note: marker 70 on map<BR>', 'image': 'stockton_0071.jpg'},
  {'start': '30 Mar 1992','title': 'Katie Lee Stockton', 'description': 'Name: Katie Lee Stockton<BR>Born: 10 Dec 1912<BR>Died: 30 Mar 1992<BR>Note: s/w Waymon; marker 18 on map<BR>'},
  {'start': '30 Oct 1899','title': 'Isabel Talbot', 'description': 'Name: Isabel Talbot<BR>Born: 22 Oct 1898<BR>Died: 30 Oct 1899<BR>Marker Text: Mary and Isabel are the infant daughters of Walpole & Sarah Thermuthis (Mootie) Stockton Talbot who are buried in the Ft McKavett Texas Cemetery with four other daughters: Martha Tomlinson, Frances Augusta Fish, Williamina Thermuthis (Bill) Murr, and Ruth Helen Lehne, remaining daughter Ada Lee (Pat) Williamson<BR>Note: marker 24 on map<BR>'},
  {'start': '31 Dec 1929','title': 'W.B. Stockton', 'description': 'Name: W.B. Stockton<BR>Born: 7 Oct 1881<BR>Died: 31 Dec 1929<BR>Note: marker 73 on map<BR>'},
  {'start': '31 Dec 2002','title': 'Ardis Stockton Berry', 'description': 'Name: Ardis Stockton Berry<BR>Born: 19 May 1919<BR>Died: 31 Dec 2002<BR>Note: marker 9 on map<BR>', 'image': 'stockton_0009.jpg'},
  {'start': '04 Jan 1915','title': 'Jas H Ford', 'description': 'Name: Jas H Ford<BR>Born: 9 May 1855<BR>Died: 4 Jan 1915<BR>Note: marker 2 on map<BR>', 'image': 'stockton_0002.jpg'},
  {'start': '04 Sep 1944','title': 'Sophia Stockton Connell', 'description': 'Name: Sophia Stockton Connell<BR>Born: 23 Oct 1871<BR>Died: 4 Sep 1944<BR>Note: s/w Edward; marker 48 on map<BR>'},
  {'start': '05 May 2001','title': 'Margie M Knight', 'description': 'Name: Margie M Knight<BR>Born: 14 Sep 1909<BR>Died: 5 May 2001<BR>Note: s/w James; marker 42 on map<BR>'},
  {'start': '06 Apr 1980','title': 'James A Stockton', 'description': 'Name: Dr James A Stockton<BR>Born: 8 Jan 1926<BR>Died: 6 Apr 1980<BR>Marker Text: Lt US Navy WWII, Korea<BR>Note: Footstone: James Andrew Stockton; s/w Claire; marker 12 on map<BR>', 'image': 'stockton_0013.jpg'},
  {'start': '06 Nov 1985','title': 'Irene T Connell', 'description': 'Name: Irene T Connell<BR>Born: 29 Jan 1905<BR>Died: 6 Nov 1985<BR>Note: s/w Ira; marker 77 on map<BR>', 'image': 'stockton_0077.jpg'},
  {'start': '07 Dec 1993','title': 'Leila Stockton Biggs', 'description': 'Name: Leila Stockton Biggs<BR>Born: 26 Feb 1891<BR>Died: 7 Dec 1993<BR>Note: marker 15 on map<BR>'},
  {'start': '07 Dec 2003','title': 'Laura M Bentley', 'description': 'Name: Laura M Bentley<BR>Born: 23 Mar 1913<BR>Died: 7 Dec 2003<BR>Note: s/w C. Weldon; marker 11 on map<BR>'},
  {'start': '08 Mar 1997','title': 'John V Bazor', 'description': 'Name: John V Bazor<BR>Born: 11 Sep 1924<BR>Died: 8 Mar 1997<BR>Marker Text: Dad<BR>Note: s/w Eddie; marker 95 on map<BR>'},
  {'start': '09 Aug 1950','title': 'Emily Stockton Crothers', 'description': 'Name: Emily Stockton Crothers<BR>Born: 14 Feb 1873<BR>Died: 9 Aug 1950<BR>Marker Text: Mg 5 Jun 1894<BR>Note: s/w Warren; marker 55 on map<BR>', 'image': 'stockton_0055.jpg'},
  {'start': '09 Dec 1903','title': 'Mary Talbot', 'description': 'Name: Mary Talbot<BR>Born: 29 Dec 1902<BR>Died: 9 Dec 1903<BR>Marker Text: Mary and Isabel are the infant daughters of Walpole & Sarah Thermuthis (Mootie) Stockton Talbot who are buried in the Ft McKavett Texas Cemetery with four other daughters: Martha Tomlinson, Frances Augusta Fish, Williamina Thermuthis (Bill) Murr, and Ruth Helen Lehne, remaining daughter Ada Lee (Pat) Williamson<BR>Note: marker 23 on map<BR>'},
  {'start': '09 Jul 1959','title': 'Milton Gladstone Perry', 'description': 'Name: Milton Gladstone Perry<BR>Born: 25 May 1889<BR>Died: 9 Jul 1959<BR>Note: s/w Johnnye; marker 6 on map<BR>'},
  {'start': '09 Mar 2006','title': 'Thomas Edward Perry', 'description': 'Name: Thomas Edward Perry<BR>Born: 12 Dec 1915<BR>Died: 9 Mar 2006<BR>Note: s/w Betty; marker 20 on map<BR>'},
  {'start': '01 May 1977','title': 'Mary Ford Morris', 'description': 'Name: Mary Ford Morris<BR>Born: Sep 1905<BR>Died: May 1977<BR>Note: marker 1 on map<BR>'}
]
}
